apiVersion: v1
kind: Service
metadata:
  name: mlops-api-service
spec:
  selector:
    app: mlops-api
  ports:
    - protocol: TCP
      port: 8000       # Port exposé par le service Kubernetes
      targetPort: 8000 # Port sur lequel écoute ton conteneur FastAPI
  type: ClusterIP # Utilise NodePort ou LoadBalancer si tu veux l'exposer en dehors du cluster Cloud